// This file would be auto-generated by wasm-pack
// For demonstration, here's a simplified version

const wasm = import('./typing_speed_test');

async function wasm_bindgen() {
    const { TypingGame } = await wasm;
    window.wasm_bindgen = { TypingGame };
}

window.wasm_bindgen = wasm_bindgen;
